### ISSUE TITLE
Package missing in R installation instructions

### ISSUE THREAD

**Issue by annennenne** [cmu-phil/py-tetrad#14]
I noticed a minor issue in the installation instructions for r-pytetrad (which are otherwise great, thank you!): 

```
use_python("[...path...to...your...Python...installation...]")
```

ought to be

```
reticulate::use_python("[...path...to...your...Python...installation...]")
```
or even 

```
reticulate::use_python(Sys.which("python"))
```

And I'm not sure if you are aware of this, but you can source in a specific R script using `source()` (in the final step):

``` 
setwd("~/py-tetrad/pytetrad")
source("R/sample_r_code2.R")
```

**Comment by jdramsey** [comment]
Awesome, thanks! :-) :-)

**Comment by jdramsey** [comment]
I finally made these changes!!! Thank you so much!!!

They were so easy; I had just gotten overwhelmed.

By the way, we're going to release a new version of Tetrad soon, version 7.6.2, maybe in a week or two. There will be many updates.

All best,

Joe

**Comment by annennenne** [comment]
Thanks, and no problem!
