### ISSUE TITLE
lavaan objects

### ISSUE THREAD

**Issue by cjpatster12** [cmu-phil/py-tetrad#25]
I'm trying to convert the fitted tetrad object into an object compatible with functions in the R lavaan library, as described in the documentation, but instructions are vague and the function $get_lavaan() doesn't seem to work, or at least doesn't work in an intuitive way.

What does $get_lavaan() do?   Can you provide brief documentation/example and confirm that its working correctly?  

This could easily be user error on my part and I'd like to rule that out first.  If not, there may be a small error in the supporting code for the function. 

Thank you for your time,
Chris

**Comment by bja43** [comment]
Hi Chris,

That method should return a string for a SEM in the format used by Lavaan. I am not very familiar with Lavern, but I know it has several methods that take a string as input to create a parametric SEM. The get_lavaan function should create and return such a string.

Best,
Bryan

**Comment by jdramsey** [comment]
@cjpatster12 Can I close this issue?

**Comment by cjpatster12** [comment]
Yes please close, thank you!
